
# ✅ FIELD MAPPING DISCOVERY:
# Web Interface "Last Induct Scan" = compAtStationData.compCurrentNodeAtStationData.firstEventTimestamp (HTML)
# This field shows ACTUAL induct arrival time, not latest scan anywhere
# Perfect for downtime monitoring between consecutive induct arrivals!

mercury:
  url: "https://mercury.amazon.com/getQueryResponse?ID=a9ebdbf5325e9395d4fbd114d3316f0c&region=na"
  scrape_interval: 120  # seconds
  
locations:
  valid: ["GA1", "GA2", "GA3", "GA4", "GA5", "GA6", "GA7", "GA8", "GA9", "GA10"]
  
# Status filters optimized for AT_STATION induct monitoring
statuses:
  # AT_STATION focused filter for real-time induct monitoring:
  valid: ["AT_STATION", "INDUCTED", "INDUCT", "STOW_BUFFER"]
  
  # Alternative: Include recently processed packages for historical analysis:
  # valid: ["AT_STATION", "INDUCTED", "INDUCT", "STOW_BUFFER", "READY_FOR_DEPARTURE"]
  
downtime:
  categories:
    - {name: "20-60", min: 20, max: 60}
    - {name: "60-120", min: 60, max: 120}  
    - {name: "120-780", min: 120, max: 780}
  break_threshold: 780
  
slack:
  webhook: "https://hooks.slack.com/triggers/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"
  report_interval: 1800  # 30 minutes
  shift_end_threshold: 2100  # seconds per location

shift:
  start: "05:20"      # 1:20 AM EDT (Toronto) = 5:20 AM UTC
  end: "12:30"        # 8:30 AM EDT (Toronto) = 12:30 PM UTC
  break_start: "08:55"  # 4:55 AM EDT = 8:55 AM UTC
  break_end: "09:30"    # 5:30 AM EDT = 9:30 AM UTC

auth:
  cookie_path: "/home/mackhun/.midway/cookie"